SAMPLE_TEXTS = {
    "software": "John Doe is a Senior Software Engineer with 8 years of experience specializing in Python, Docker, and Kubernetes. John Doe holds a Master of Science from MIT in New York, NY. Certified in AWS Certified Solutions Architect. Email: john.doe@email.com, Phone: (555) 123-4567. He recently completed the Migration to Cloud project successfully.",
    "healthcare": "Dr. Sarah Johnson, MD, is a Cardiologist with 15 years of experience in Patient Care and Clinical Research. She graduated from Harvard with a Ph.D. Located in Boston, MA. Email: sarah.j@hospital.org. Phone: 987-654-3210. Certified in Medical Board Certifed.",
    "legal": "Attorney Michael Chang has 10 years of experience in Corporate Governance and Intellectual Property. He works at a top firm in London, UK. He earned his Juris Doctor (J.D.) from Oxford. Email: mchang@lawfirm.co.uk | Phone: +1-555-123-4567. Key project: Mergers and Acquisitions Due Diligence 2023.",
    "arts": "Emily Chen, a Creative Director, brings 6 years of expertise in UI/UX Design, Adobe Photoshop, and Typography. She has a Bachelor of Arts from NYU and is based in San Francisco, CA. Contact: e.chen@design.net, 555.123.4567. Project: E-commerce Website Redesign.",
    "finance": "Robert Smith is a Financial Analyst with 4 years of experience. Skills: Financial Modeling, Excel VBA, Risk Analysis. Holds an MBA from Stanford University. Based in Chicago, IL. Certified in CFA. Phone: 5551234567. Email: rsmith_finance@domain.com.",
    "marketing": "Jessica Taylor, Marketing Manager, specializes in SEO, Content Strategy, and Brand Management over her 7 years career. She holds a B.S. from UCLA and is located in Austin, TX. Email: jess.taylor@marketing.com, Phone: (555) 987-6543.",
    "hr": "David Wilson is an HR Manager based in Seattle, WA. With 12 years of experience, his top skills are Talent Acquisition, Employee Relations, and HRIS. He holds a B.A. from University of Michigan. Certified in SHRM-CP. Contact: dwilson_hr@company.co, 555-111-2222.",
    "engineering": "Alice Brown, Mechanical Engineer, holds a B.Tech from Georgia Tech. She has 5 years of experience specializing in AutoCAD, SolidWorks, and Thermodynamics. Based in Toronto, ON. Certified in Six Sigma Black Belt. Email: abrown@eng.net, Phone: 555.999.8888.",
    "hospitality": "James Miller, Hotel Manager at a 5-star resort in Berlin, Germany. He has 10 years of experience with Guest Relations, Revenue Management, and Opera PMS. Certified in Food Safety. Email: jmiller@hotel.com, Phone: +49-555-1234.",
    "trades": "William Davis is a Master Electrician with 20 years of experience in Electrical Wiring, Blueprint Reading, and OSHA Safety. Based in Remote. Email: wdavis_trades@email.com, Phone: (555) 333-4444. He successfully led the Enterprise ERP Implementation electrical grid upgrade."
}
